### ISSUE TITLE
Important results in the missing Appendix  

### ISSUE THREAD

**Issue by davidkillerhahaha** [jbr-ai-labs/mamba#2]
Hi~
It's really a fantastic work ! Our team focus on the model based learning method for multi agents system too and want to follow your work. 
However, some details and experimental results are presented in the appendix and it seems that Supplementary Materials NOT be contained in the [camera-ready version](https://dl.acm.org/doi/abs/10.5555/3535850.3535894). The missing of appendix really confuses us about the specific details of this work. May I ask when do you prepare to release the complete version of paper please?
It's really a excellent work! Thanks!

**Comment by vladimirrim** [comment]
Hi, the full version can be found at [https://arxiv.org/abs/2205.15023](https://arxiv.org/abs/2205.15023)
