### ISSUE TITLE
Potential duplication of the code in DreamerWorker.py

### ISSUE THREAD

**Issue by GoingMyWay** [jbr-ai-labs/mamba#3]
Hi, I found this [line](https://github.com/jbr-ai-labs/mamba/blob/main/agent/workers/DreamerWorker.py#L120) is called twice. Is it a potential duplication of the code?

**Comment by vladimirrim** [comment]
Hi, no, we add two items here on purpose, this technique is called absorbing states (you can read more about it [here](https://arxiv.org/pdf/1809.02925.pdf). Basically we are adding a state that loops to itself
